---
title: "Future of Tornado Outbreaks"
author: "Dr. Searcy"
date: "2024-03-18"
output: html_document
---



```{r}
install.packages("metR")
library(metR)
```

```{r}
library(ncdf4)
test = nc_open(filename = "/Volumes/R1 Dr. Searcy/New folder/ta_6hrLev_CNRM-CM6-1_historical_r1i1p1f2_gr_198001010600-198007010000.nc")

names(test$var)
#extent(c(-125, -67, 24, 50))

LatIdx = which(test$dim$lat$vals > 24 & test$dim$lat$vals < 50)
LonIdx = which(test$dim$lon$vals > 235 & test$dim$lon$vals < 293)
myvariable <- ncvar_get(test, test$var$ta)[LonIdx, LatIdx]
```

```{r}
library(raster)
library(ncdf4)

fname = "/Volumes/R1 Dr. Searcy/New folder/ta_6hrLev_CNRM-CM6-1_historical_r1i1p1f2_gr_198001010600-198007010000.nc"

#load the raster brick file. 
avgTemp80 <- brick(fname)
avgTemp80

#contiguous United States Extent---matches the population
  ext = raster::extent(c(235, 293, 24, 50))
#temperatures are in Kelvin
  #multiple layers for every day try ta_80$
  ta_80 = crop(avgTemp80, ext)
  
  plot(ta_80[[1]])
```

```{r}
fname = "E:/Zoe/Projects/TornEnvironmentsandGHGs/tas_Amon_CNRM-CM6-1_historical_r1i1p1f2_gr_185001-201412.nc"

tas <- brick(fname)

#contiguous United States Extent---matches the population
  ext = raster::extent(c(235, 293, 24, 50))
#temperatures are in Kelvin
  #multiple layers for every day try ta_80$
  tas_US = crop(tas, ext)
  plot(tas_US[[1]])

tas_1950 <- mean(tas_US[[1:12]])  
plot(tas_1950)
```

```{r}
fname = "E:/Zoe/Projects/TornEnvironmentsandGHGs/ta_Amon_CNRM-CM6-1_historical_r1i1p1f2_gr_185001-201412.nc"

ta <- brick("E:/Zoe/Projects/TornEnvironmentsandGHGs/ta_Amon_CNRM-CM6-1_historical_r1i1p1f2_gr_185001-201412.nc", package="raster")
test <- raster(ta, layer = 2)
#contiguous United States Extent---matches the population
  ext = raster::extent(c(235, 293, 24, 50))
#temperatures are in Kelvin
  #multiple layers for every day try ta_80$
  ta_US = crop(test, ext)
  plot(ta_US)
```

```{r}
  #install.packages('terra', repos='https://rspatial.r-universe.dev')
library(terra)
x <- rast('SSS.nc')
```